server:
  port: 8581
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: HELLOUSER
    password: HELLOUSER
mybatis:
  mapper-locations: sql-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  #type-aliases-package:
  type-aliases-package: project.member.vo